SET(OS_SHEBANG "#!/bin/bash")
SET(ClangTools_install_command "")
SET(Git_install_command "")
SET(Doxygen_install_command "brew install doxygen")
SET(OpenMP_install_command "")
SET(Threads_install_command "")
SET(Numa_install_command "")
SET(TBB_install_command "brew install tbb")