SET(OS_SHEBANG "#!/bin/bash")
SET(ClangTools_install_command "")
SET(Git_install_command "brew install git")
SET(Doxygen_install_command "brew install doxygen")
SET(OpenMP_install_command "brew install clang-omp")
SET(Threads_install_command "")
SET(Numa_install_command "")
SET(TBB_install_command "brew install tbb")
SET(MPI_install_command "brew install open-mpi")
SET(MKDocs_install_command "pip install --user mkdocs mkdocs-material")
SET(Valgrind_install_command "")
SET(GLUT_install_command "")
SET(PythonInterp_install_command "brew install python python@2")
SET(PythonLibs_install_command "")
SET(Coverage_install_command "brew install lcov gcov gcovr")