SET(OS_SHEBANG "#!/bin/bash")
SET(ClangTools_install_command "sudo apt-get install -y clang-3.9 clang-format-3.9 clang-tidy-3.9")
SET(MPI_install_command "sudo apt-get install -y libopenmpi-dev")
SET(Git_install_command "sudo apt-get install -y git")
SET(MKDocs_install_command "pip install --user mkdocs mkdocs-material")
SET(Valgrind_install_command "sudo apt-get install -y valgrind")
SET(Doxygen_install_command "sudo apt-get install -y doxygen graphviz")
SET(OpenMP_install_command "sudo apt-get install -y libomp-dev")
SET(Threads_install_command "sudo apt-get install -y libpthread-stubs0-dev")
SET(Numa_install_command "sudo apt-get install -y libnuma-dev")
SET(TBB_install_command "sudo apt-get install -y libtbb-dev")
SET(GLUT_install_command "sudo apt-get install -y freeglut3-dev")
SET(PythonInterp_install_command "sudo apt-get install -y python python3 python-pip python3-pip")
SET(PythonLibs_install_command "sudo apt-get install -y python2.7-dev")
SET(Coverage_install_command "sudo apt-get install -y lcov gcov gcovr")