#!/bin/bash
# -----------------------------------------------------------------------------
#
# Copyright (C) 2021 CERN & Newcastle University for the benefit of the
# BioDynaMo collaboration. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# See the LICENSE file distributed with this work for details.
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# -----------------------------------------------------------------------------

# This script generates ROOT dictionaries for NON CMake builds

if [ $# -lt 4 ]; then
    echo "Wrong number of arguments"
    echo "Usage: bdm-code-generation DICTIONARY BDM_CONFIG [CXX_FLAGS] -h header1.h [header2.h ...]"
    echo "   DICTIONARY file name of the dictionary that gets generated"
    echo "              (e.g., my-sim_dict.cc)"
    echo "   BDM_CONFIG bdm config command. Used to pass optional compiler and build type"
    echo "              (e.g., \"bdm-config --debug --opt\")"
    echo "   CXX_FLAGS  additional CXX flags (optional). Add includes or defines only!"
    echo "   HEADERS    at least one header file containing the biodynamo definitions"
    exit
fi

DICT=$1
shift
BDM_CONFIG=$1
shift
if [ $1 != "-h" ]; then
  ADDITIONAL_CXX_FLAGS=$1
  shift
  while [ $1 != "-h" ]; do
    ADDITIONAL_CXX_FLAGS="$ADDITIONAL_CXX_FLAGS $1"
    shift
  done
fi
shift
HEADERS=$@

SELECTIONFILE=$(${BDM_CONFIG} --cmakedir)/selection.xml

CXX_INCLUDES=$(${BDM_CONFIG} --cxxincludes | sed 's|-isystem |-I|g')

CXX_DEFINES=$(${BDM_CONFIG} --cxxdefines)

genreflex ${HEADERS} -o ${DICT} --select=${SELECTIONFILE} ${CXX_DEFINES} ${CXX_INCLUDES} $ADDITIONAL_CXX_FLAGS

# Generate bdm dictionary and append to DICT
BDM_DICT=$(mktemp)
bdm-dictionary $BDM_DICT $HEADERS
echo "" >> $DICT
echo "// -------------------------------------------------------------------" >> $DICT
echo "// Start BioDynaMo dictionary" >> $DICT
cat $BDM_DICT >> $DICT
rm $BDM_DICT
