#!/usr/bin/env bash

# Adapted from https://github.com/pyenv/pyenv-installer/blob/master/bin/pyenv-installer

set -e

temp_dir=$(mktemp -d)
BDM_SRC="${temp_dir}/biodynamo"

Colorize() {
  if [ -t 1 ]; then printf "\e[%sm%s\e[m" "$1" "$2"
  else echo -n "$2"
  fi
}

FailedCheckout() {
  Colorize 1 "ERROR"
  echo "Failed to git clone $1"
  exit -1
}

# TODO: replace branch with 'master' when merging
Checkout() {
  [ -d "$2" ] || git clone --branch one-line-install "$1" "$2" || FailedCheckout "$1"
}

# Check if git is installed
if ! command -v git 1>/dev/null 2>&1; then
  Colorize 1 "ERROR"
  echo "Git is not installed, can't continue." >&2
  exit 1
fi

if [ -n "${USE_GIT_URI}" ]; then
  GITHUB="git://github.com"
else
  GITHUB="https://github.com"
fi

# Clone BioDynaMo
Checkout "${GITHUB}/BioDynaMo/biodynamo.git" "${BDM_SRC}"

# Enable silent installation if we are running Github Actions
if [ ! -z ${GITHUB_ACTIONS+x} ]; then
  export SILENT_INSTALL=1
fi

# Run ./install.sh
BDM_CMAKE_FLAGS="-Dtest=off -Dnotebooks=on -Dsbml=ON" ${BDM_SRC}/install.sh
