%native(RATIONAL);
%native(EXACTVECTOR);
%native(TRIANGLE3D);
%native(EDGE);
%native(EDGEHASHKEY);
%native(TRIANGLEHASHKEY);
%native(TETRAHEDRON);
%native(SPACENODE);
%native(SIMPLETRIANGULATIONNODEORGANIZER);
%native(OPENTRIANGLEORGANIZER);

%native(SUBSTANCE);
%native(INTRACELLULARSUBSTANCE);
%native(PHYSICALNODE);
%native(PHYSICALNODEMOVEMENTLISTENER);
%native(SPATIALORGANIZATIONNODEMOVEMENTLISTENER);
