#ifndef BDM_VERSION_H_
#define BDM_VERSION_H_

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if BDM_VERSION_CODE >= BDM_VERSION(1,0,0)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define BDM_RELEASE "0.9.0"
#define BDM_RELEASE_DATE "Jun 22 2016"
#define BDM_RELEASE_TIME "16:27:00"
#define BDM_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
#define BDM_VERSION_CODE BDM_VERSION(0,9,0)

namespace bdm {

class Version {
   public:
      static const char *Release() { return BDM_RELEASE; }
      static const char *ReleaseDate() { return BDM_RELEASE_DATE; }
      static const char *ReleaseTime() { return BDM_RELEASE_TIME; }
      static int         VersionCode() { return BDM_VERSION_CODE; }
      static const char *BuiltDate() { return __DATE__; }
      static const char *BuiltTime() { return __TIME__; }
};

}

#endif

