#!/bin/bash

# This script generates ROOT dictionaries for NON CMake builds

if [ $# -lt 3 ]; then
    echo "Wrong number of arguments"
    echo "Usage: bdm_code_generation DICTIONARY BDM_CONFIG header1.h [header2.h ...]"
    echo "   DICTIONARY file name of the dictionary that gets generated"
    echo "              (e.g., my-sim_dict.cc)"
    echo "   BDM_CONFIG bdm config command. Used to pass optional compiler and build type"
    echo "              (e.g., \"bdm-config --cxx-compiler=g++ --build-type=Release\")"
    echo "   HEADERS    at least one header file containing the biodynamo definitions"
    exit
fi

DICT=$1
shift
BDM_CONFIG=$1
shift
HEADERS=$@

SELECTIONFILE=$(${BDM_CONFIG} --cmakedir)/selection.xml

CXX_INCLUDES=$(${BDM_CONFIG} --cxxincludes)

CXX_DEFINES=$(${BDM_CONFIG} --cxxdefines)

genreflex ${HEADERS} -o ${DICT} --select=${SELECTIONFILE} ${CXX_DEFINES} ${CXX_INCLUDES}
