#!/usr/bin/env python3
# -----------------------------------------------------------------------------
#
# Copyright (C) 2021 CERN & Newcastle University for the benefit of the
# BioDynaMo collaboration. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# See the LICENSE file distributed with this work for details.
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# -----------------------------------------------------------------------------

# This script generates BioDynaMo dictionaries
import argparse
import os

def AppendPrefix(prefix, prefixes):
    if prefix.endswith("/"):
        prefixes.append(prefix)
    else:
        prefixes.append("{}/".format(prefix))

def RemoveLongestPrefix(search, prefixes):
    lengths = [len(prefix) for prefix in prefixes if search.startswith(prefix)]
    if lengths:
        return search[max(lengths):] 
    else:
        return search

def ReplaceSpecialPaths(include_dir, environmentals):
    for e in environmentals:
        path = os.getenv(e)
        if not path.endswith("/"):
            path = "{}/".format(path)
        if include_dir.startswith(path):
            return 'std::getenv("{0}") << "/{1}"'.format(e, include_dir[len(path):])
    return '"{}"'.format(include_dir)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='bdm-dictionary',
        description='This script generates the biodynamo c++ dictionary file.',
        epilog='')
    
    parser.add_argument('--output', action='store', type=str, required=True, help='Filename of the bdm dictionary that will be generated.')
    parser.add_argument('--out-of-source', action='store_true', help='Generate bdm dictionary for an out-of-source build. e.g. a simulation.')
    parser.add_argument('--include-dirs', nargs='+', type=str, required=True, help='At least one directory that contains the header files.')
    parser.add_argument('--headers', nargs='+', type=str, required=True, help='At least one header file containing biodynamo definitions.')

    args = parser.parse_args()

    with open(args.output, "w") as f:
        f.write("""
// BioDynaMo dictionary.
// This file was generated.
// Do NOT change it. 
// Changes will be lost the next time this file is generated.

#include "core/util/jit.h"
#include <cstdlib>
#include <sstream>
namespace {

static struct BioDynaMoDictInit {
  BioDynaMoDictInit() {
    std::stringstream idirs; 
""")

        prefixes = []
        environmentals = ["ParaView_DIR", "ROOTSYS", "BDMSYS"]
        if not args.out_of_source:
            include_suffix = ["/include/paraview-5.8", "/include", "/include"]
            cnt = 0
            for e in environmentals: 
                f.write('    idirs << std::getenv("{0}") << "{1}" << ":";\n'.format(e, include_suffix[cnt]))
                cnt = cnt + 1
            for id in args.include_dirs:
                AppendPrefix(id, prefixes)
        else:
            for e in environmentals: 
              AppendPrefix(os.getenv(e), prefixes)
            for id in args.include_dirs:
                id_processed = ReplaceSpecialPaths(id, environmentals) 
                if id_processed != "":
                  AppendPrefix(id, prefixes)
                  f.write('    idirs << {0} << ":";\n'.format(id_processed))
        
        for h in args.headers:
            f.write('    bdm::JitHeaders::Register("{0}");\n'.format(RemoveLongestPrefix(h, prefixes)))

        f.write("""
    idirs << std::getenv("ROOT_INCLUDE_PATH");
    setenv("ROOT_INCLUDE_PATH", idirs.str().c_str(), true);
  }
} bdm_dict_initializer;

}

  
""")

